
<div class="sidebar_wrapper">
			
	<div class="sidebar_box sidebar_pa">
				
		<?php 
			
			// future versions of bulk nav plugin will support custom post types, for now this is calling the widget generated by plugin
			
			dynamic_sidebar( '_ilaw_sm_default_sidebar' ); ?>
				
		</div><!-- sidebar_box -->
		
	</div><!-- sidebar_wrapper -->

